server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://promptmanager.c030omec28ek.us-east-1.rds.amazonaws.com:5432/promptmanager   # 👈 your DB name here
    username: postgres                             # 👈 your DB user
    password: pID5fL0KVQVvNJpRHNQD                             # 👈 your DB password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update     # creates/updates tables automatically
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    #prefer-ip-address: true
    prefer-ip-address: false
    hostname: user-service-promptmanager.microservice-namespace  # 👈 ECS Cloud Map DNS name
    non-secure-port: 8081  

