apiVersion: v1
kind: ConfigMap

metadata:
  name: promptmanager-config
  namespace: promptmanager

data:

  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/promptmanager

  SPRING_RABBITMQ_HOST: rabbitmq

  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  PROMPT_SERVICE_URL: http://api-gateway:8080

  OLLAMA_URL: http://ollama:11434/api/generate