apiVersion: v1
kind: Secret

metadata:
  name: promptmanager-secret
  namespace: promptmanager

type: Opaque

stringData:

  SPRING_DATASOURCE_USERNAME: postgres

  SPRING_DATASOURCE_PASSWORD: root

  JWT_SECRET: mySuperSecretJWTKeymySuperSecretJWTKeymySuperSecretJWTKey