apiVersion: apps/v1
kind: Deployment

metadata:
  name: ml-service
  namespace: promptmanager

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ml-service

  template:
    metadata:
      labels:
        app: ml-service

    spec:
      containers:

        - name: ml-service

          image: vikasbhalla0004/ml-service-promptmanagerfinal:latest

          ports:
            - containerPort: 8002