server:
  port: 8082

spring:
  application:
    name: prompt-service

  datasource:
    #url: jdbc:postgresql://promptmanager.c030omec28ek.us-east-1.rds.amazonaws.com:5432/promptmanager
    #username: postgres
    #password: pID5fL0KVQVvNJpRHNQD
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/promptmanager}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}                            
    password: ${SPRING_DATASOURCE_PASSWORD:root} 
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Eureka registration
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    #hostname: localhost
    instance-id: prompt-service:8082
    #prefer-ip-address: false
    #hostname: prompt-service-promptmanager.microservice-namespace  # 👈 ECS Cloud Map DNS name
    #non-secure-port: 8082
logging:
  level:
    org.springframework: INFO
    com.promptmanager: DEBUG
feign:
  client:
    config:
      default:
        loggerLevel: full

